Update github actions for ocp4

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -3,7 +3,7 @@ name: Build
 on:
   push:
     branches:
-      - main
+      - develop
     paths:
       - services/**
       - migrations/**
@@ -35,7 +35,7 @@ jobs:
           - name: docman
           - name: filesystem-provider
           - name: nris
-          - name: digdag
+          - name: minespace
     steps:
       - name: Check out the repo
         uses: actions/checkout@v2
@@ -65,6 +65,7 @@ jobs:
           - name: backend
           - name: docman
           - name: nris
+          - name: minespace
     steps:
       - name: Install oc
         uses: redhat-actions/oc-installer@v1
@@ -94,7 +95,7 @@ jobs:
           - name: docman
           - name: filesystem-provider
           - name: nris
-          - name: digdag
+          - name: minespace
     steps:
       - name: Install oc
         uses: redhat-actions/oc-installer@v1
@@ -126,8 +127,8 @@ jobs:
           - name: metabase-postgres
           - name: docman
           - name: filesystem-provider
-          # - name: nris
-          - name: digdag
+          - name: nris
+          - name: minespace
     steps:
       - name: Install oc
         uses: redhat-actions/oc-installer@v1
@@ -142,37 +143,36 @@ jobs:
           ${{ secrets.NS_TOOLS }}/${{ matrix.name }}:${{ env.INITIAL_TAG }} \
           ${{ secrets.NS_TOOLS }}/${{ matrix.name }}:${{ env.TAG }}
 
-  rollout:
-    name: rollout
-    needs: tag
-    runs-on: ubuntu-20.04
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - name: nginx
-          - name: postgresql
-          - name: frontend
-          - name: backend
-          - name: tusd
-          - name: docgen
-          - name: dbbackup
-          - name: redis
-          - name: metabase
-          - name: metabase-postgres
-          - name: docman
-          - name: filesystem-provider
-          # - name: nris
-          - name: digdag
-    steps:
-      - name: Install oc
-        uses: redhat-actions/oc-installer@v1
-        with:
-          version: "4.6"
-      - name: oc login
-        run: |
-          oc login --token=${{ secrets.BUILD_TOKEN }} --server=${{ secrets.CLUSTER_API }}
-      - name: rollout to dev
-        run: |
-          oc -n ${{ secrets.NS_DEV }} rollout latest ${{ matrix.name }} || true
-        continue-on-error: true
+  # rollout:
+  #   name: rollout
+  #   needs: tag
+  #   runs-on: ubuntu-20.04
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - name: nginx
+  #         - name: postgresql
+  #         - name: frontend
+  #         - name: backend
+  #         - name: tusd
+  #         - name: docgen
+  #         - name: dbbackup
+  #         - name: redis
+  #         - name: metabase
+  #         - name: metabase-postgres
+  #         - name: docman
+  #         - name: filesystem-provider
+  #         - name: nris
+  #   steps:
+  #     - name: Install oc
+  #       uses: redhat-actions/oc-installer@v1
+  #       with:
+  #         version: "4.6"
+  #     - name: oc login
+  #       run: |
+  #         oc login --token=${{ secrets.BUILD_TOKEN }} --server=${{ secrets.CLUSTER_API }}
+  #     - name: rollout to dev
+  #       run: |
+  #         oc -n ${{ secrets.NS_DEV }} rollout latest ${{ matrix.name }} || true
+  #       continue-on-error: true
diff --git a/.github/workflows/promote-to-prod.yaml b/.github/workflows/promote-to-prod.yaml
--- a/.github/workflows/promote-to-prod.yaml
+++ b/.github/workflows/promote-to-prod.yaml
@@ -1,6 +1,9 @@
 name: Promote to prod
 
 on:
+  push:
+    branch:
+      - master
   workflow_dispatch:
 
 env:
@@ -25,16 +28,19 @@ jobs:
     strategy:
       matrix:
         include:
-          - name: nginx
-          - name: postgresql
           - name: frontend
           - name: backend
           - name: flyway
-          - name: tusd
-          - name: docgen
           - name: dbbackup
+          - name: docgen
+          - name: postgresql96
+          - name: nginx
+          - name: tusd
           - name: metabase
           - name: metabase-postgres
+          - name: docman
+          - name: filesystem-provider
+          - name: nris
     steps:
       - name: Install oc
         uses: redhat-actions/oc-installer@v1
@@ -49,33 +55,33 @@ jobs:
           ${{ secrets.NS_TOOLS }}/${{ matrix.name }}:${{ env.ORIG_TAG }} \
           ${{ secrets.NS_TOOLS }}/${{ matrix.name }}:${{ env.PROMOTE_TAG }}
 
-  rollout-prod:
-    name: rollout-prod
-    needs: promote-to-prod
-    runs-on: ubuntu-20.04
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - name: nginx
-          # - name: postgresql
-          - name: frontend
-          - name: backend
-          - name: tusd
-          - name: docgen
-          - name: dbbackup
-          # - name: redis
-          # - name: metabase
-          # - name: metabase-postgres
-    steps:
-      - name: Install oc
-        uses: redhat-actions/oc-installer@v1
-        with:
-          version: "4.6"
-      - name: oc login
-        run: |
-          oc login --token=${{ secrets.BUILD_TOKEN }} --server=${{ secrets.CLUSTER_API }}
-      - name: rollout to prod
-        run: |
-          oc -n ${{ secrets.NS_PROD }} rollout latest ${{ matrix.name }} || true
-        continue-on-error: true
+  # rollout-prod:
+  #   name: rollout-prod
+  #   needs: promote-to-prod
+  #   runs-on: ubuntu-20.04
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - name: nginx
+  #         - name: postgresql
+  #         - name: frontend
+  #         - name: backend
+  #         - name: tusd
+  #         - name: docgen
+  #         - name: dbbackup
+  #         - name: redis
+  #         - name: metabase
+  #         - name: metabase-postgres
+  #   steps:
+  #     - name: Install oc
+  #       uses: redhat-actions/oc-installer@v1
+  #       with:
+  #         version: "4.6"
+  #     - name: oc login
+  #       run: |
+  #         oc login --token=${{ secrets.BUILD_TOKEN }} --server=${{ secrets.CLUSTER_API }}
+  #     - name: rollout to prod
+  #       run: |
+  #         oc -n ${{ secrets.NS_PROD }} rollout latest ${{ matrix.name }} || true
+  #       continue-on-error: true
