checking out memory usage

diff --git a/.github/workflows/minespace.cypress.yaml b/.github/workflows/minespace.cypress.yaml
--- a/.github/workflows/minespace.cypress.yaml
+++ b/.github/workflows/minespace.cypress.yaml
@@ -44,9 +44,12 @@ jobs:
       - name: Run app
         run: |
           ARTIFACTORY_TOKEN=${{ secrets.ARTIFACTORY_TOKEN }} EXTRA_SERVICES=minespace make be-minimal
-      - name: Seed database
+      - name: Seed database with Memory Monitoring
         run: |
-          make ENTRIES=10 seeddb
+          echo "Starting memory monitoring..."
+          free -h
+          echo "Running seeddb step..."
+           /usr/bin/time -v make ENTRIES=10 seeddb || (echo "Seed DB failed. Checking memory usage..."; free -h)
       - name: Run cypress tests
         run: yarn workspace @mds/minespace-web cypress run
         env:
